#!/usr/bin/env bash

release_file=/etc/os-release

function install_flatpak_apps() {
  echo "Installing apps..."

	# calculator
	echo "SpeedCrunch"
	flatpak -y install flathub org.speedcrunch.SpeedCrunch

	# clipboard manager
	echo "CopyQ"
	flatpak -y install flathub com.github.hluk.copyq

	# password manager
	echo "KeePassXC"
	flatpak -y install flathub org.keepassxc.KeePassXC 

	# LibreOffice
	echo "LibreOffice"
	flatpak -y install flathub org.libreoffice.LibreOffice

	# color picker
	echo "Pick"
	flatpak -y install flathub org.kryogenix.Pick

	# on-screen ruler
	echo "KRuler"
	flatpak -y install flathub org.kde.kruler

	# image viewer
	echo "nomacs"
	flatpak -y install flathub org.nomacs.ImageLounge

	# rastor graphics editor
	echo "Gimp"
	flatpak -y install flathub org.gimp.GIMP

	# vector graphics editor
	echo "Inkscape"
	flatpak -y install flathub org.inkscape.Inkscape

	# email client
	echo "Thunderbird"
	flatpak -y install flathub org.mozilla.Thunderbird

	# google chrome
	echo "Google Chrome"
	flatpak -y install flathub com.google.Chrome

	# mozilla firefox
	echo "Mozilla Firefox"
	flatpak -y install flathub org.mozilla.firefox

	# microsoft edge
	echo "Microsoft Edge"
	flatpak -y install flathub com.microsoft.Edge

	# opera
	echo "Opera"
	flatpak -y install flathub com.opera.Opera

	# document viewer
	echo "Okular"
	flatpak -y install flathub org.kde.okular

	# figma wrapper
	echo "Figma"
	flatpak -y install flathub io.github.Figma_Linux.figma_linux

	# e-books manager
	echo "calibre"
	flatpak -y install flathub com.calibre_ebook.calibre 

	# proton mail bridge
	echo "Proton Mail Bridge"
	flatpak -y install flathub ch.protonmail.protonmail-bridge

	# visual studio code
	echo "Visual Studio Code"
	flatpak -y install flathub com.visualstudio.code 

	# qbittorrent
	echo "qBittorrent"
	flatpak -y install flathub org.qbittorrent.qBittorrent 
}

# if not root do nothing
if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required."
  exit 1
fi

# universal script for upgrade eg. apt
if ! command -v package-man-u > /dev/null 2>&1
then
  curl -O "$pman_i_url"
  chmod +x "$pman_i_name"
  ./"$pman_i_name"
  rm ./"$pman_i_name"
fi

package-man-u

if command -v flatpak > /dev/null 2>&1
then
        echo "Flatpak is installed."
else
        echo "Flatpak isn't installed."
        echo "Installation..."

        if grep -q "Ubuntu" $release_file
        then
            apt -y install flatpak
        fi

        echo "Installation completed."
        echo "Adding Flathub repository..."

        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi

install_flatpak_apps
